---
- name: Backup Redmine Database
  hosts: redmine_server
  become: yes
  vars:
    db_user: root
    db_password: example
    db_name: redmine
    backup_path: /home/user/backups/redmine_backup.sql

  tasks:
    - name: Create backup directory
      file:
        path: /home/user/backups
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Dump MySQL database
      command: >
        docker exec redmine-db-1 sh -c "mysqldump -u {{ db_user }} -p{{ db_password }} {{ db_name }} > /var/lib/mysql-backups/redmine_backup.sql"
      args:
        creates: "{{ backup_path }}"
